#Escriba el algoritmo que al capturar un número entero convierta grados centígrados a kelvin, si captura un número flotante diga si es mayor a 10.5, y si captura un carácter escriba su nombre.
num = int(input("ingresa los grados centigrados"))

KELVIN = num + 273.15
print("la convercion de centigrados a KELVIN es:", KELVIN)


if num > 10.5:
    print("el numero flotante es mayor a 10.5")
#VERIFICAR SI UN NUMERO ES FLOTANTE.
elif  dato.replace (".",1). isdigit():
#convierte el dato a numero entero.
num = float (dato)
#verifica si es mayor a 10.5
if num > 10.5:
print("el numero flotante es mayor a 10.5")
 
 else: 
  print("el numero flotante no es mayor a 10,5")
#verifica si el dato es un caracter (una letra o un simbolo)
elif     len (dato) = = 1 :
print (f" el caracter ingresado es {"dato"} ")
